name: Gradle
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Gradle chmod
      run: chmod +x gradlew
    - name: Gradle build
      run: ./gradlew build
    - name: Gradle lintKotlin
      run: ./gradlew lintKotlin
